# Generated by Django 5.2.7 on 2025-10-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brewery', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
    ]
